M48
; DRILL file {KiCad 9.0.5} date 2025-10-16T19:16:23+1000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-16T19:16:23+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1693
%
G90
G05
T1
X5.6024Y-2.5004
X5.6024Y-2.728
T2
X4.8425Y-3.8319
X4.9606Y-3.8319
T3
X4.5205Y-3.648
T4
X2.4409Y-1.4591
X2.4409Y-3.889
X5.4567Y-1.4591
X5.4567Y-3.889
T5
X3.8839Y-2.0118
X3.8839Y-3.2717
M30
